from rest_framework.routers import DefaultRouter
from django.urls import path
from .api.views import CurrencyViewSet, ExchangeRateViewSet, GetLocalCurrencyAPIView

router = DefaultRouter()
router.register('currencies', CurrencyViewSet, basename='currency')
router.register('exchangerates', ExchangeRateViewSet, basename='exchangerate')

urlpatterns = router.urls

urlpatterns = [
    *router.urls,  # Include URLs generated by the router
    path('get-localcurrency/', GetLocalCurrencyAPIView.as_view(), name='get-localcurrency'),
]


# from django.urls import path, include
# from rest_framework.routers import DefaultRouter
# from .views import CurrencyViewSet, ExchangeRateViewSet, GetLocalCurrencyAPIView

# router = DefaultRouter()
# router.register(r'currencies', CurrencyViewSet, basename='currency')
# router.register(r'exchange-rates', ExchangeRateViewSet, basename='exchangerate')

# urlpatterns = [
#     path('api/', include(router.urls)),
#     path('api/get-local-currency/', GetLocalCurrencyAPIView.as_view(), name='get-local-currency'),
# ]